services:
  - type: web
    name: gestao-industrial
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    healthCheckPath: /health
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: gestao-industrial-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "480"
      - key: APP_NAME
        value: Gestão Industrial
      - key: CORS_ORIGINS
        value: ""
      - key: APP_URL
        value: https://gestao-industrial-6nai.onrender.com
      - key: RESEND_API_KEY
        sync: false
      - key: RESEND_FROM_EMAIL
        sync: false

databases:
  - name: gestao-industrial-db
    plan: free
